package tpls

import (
	"bytes"
	"text/template"
)

const HttpRouteTpl = `// Code generated by go3gen. DO NOT EDIT.
package route

import (
	"time"

	"github.com/gin-gonic/gin"
	"go.opentelemetry.io/otel/attribute"

	"{{.Project}}/common"
	"{{.Project}}/common/core/log"
	"{{.Project}}/common/core/otel/prometheus"
	"{{.Project}}/common/core/otel/tracing"


	"{{.AppPkgPath}}/cmd/{{.EntryName}}/handler"
	"{{.AppPkgPath}}/cmd/{{.EntryName}}/types"
)

func generated(r *gin.Engine) {

	{{- range .Groups}}
	// ----------------------------------- {{.GroupName}} -----------------------------------
	{{- range .FunList}}
	// {{.FunMark}}
	r.POST("{{.URI}}", func(ctx *gin.Context) {
		var (
			st = time.Now()
			_ctx = common.HTTPMetadata(ctx)
			req = &types.{{.ReqName}}{}
			resp = &types.{{.RespName}}{}
			err error
		)
		reqRaw,raw,_common, err := reqJSON(ctx)
		if err != nil {
			JSONError(ctx, common.ErrParams)
			return
		}
		if _common != nil {
			_ctx = context.WithValue(_ctx,"__COMMON__",_common)
		}
		_ctx, span := tracing.StartSpan(_ctx, "http:{{.URI}}")
		defer func() {
			span.End()
			prometheus.HistogramVec.Timing("http_seconds", map[string]string{
				"entry":  "{{$.EntryName}}",
				"api":    "{{.URI}}",
				"ret":    prometheus.RetLabel(err),
			}, st)
			log.With().TraceID(_ctx).Field("req", raw).Field("resp", resp).Field("err", err).Info("on-http")
		}()
		if err = common.BindBody(reqRaw, &req); err != nil {
			JSONError(ctx, common.ErrParams)
			return
		}
		resp, err = handler.{{.FunName}}(_ctx, req)
		JSON(ctx, resp, err)
	})
	{{- end}}
	{{- end}}
}
`

type HttpEntry struct {
	Project      string
	AppName      string
	AppNameUF    string
	AppPkgPath   string
	EntryName    string
	EntryPath    string
	EntryPkgPath string
	Groups       []*EntryGroup
}

type EntryGroup struct {
	Group       string
	GroupName   string
	Middlewares []string
	FunList     []EntryFunItem
}

type EntryFunItem struct {
	FunName     string
	FunMark     string
	ReqName     string
	RespName    string
	Middlewares []string
	URI         string
	URI2        string
}

func (s *HttpEntry) Execute(t string) ([]byte, error) {
	buf := new(bytes.Buffer)
	tmpl, err := template.New("httpEntry").Parse(t)
	if err != nil {
		return nil, err
	}
	if err := tmpl.Execute(buf, s); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
