package tpls

import (
	"bytes"
	"text/template"
)

const microProviderTpl = `// Code generated by go3gen. DO NOT EDIT.
package provider

var (
	{{- range .MicroList}}
	{{.}} {{.}}Interface
	{{- end}}
)
`

type MicroProvider struct {
	MicroList []string
}

func (s *MicroProvider) Execute() ([]byte, error) {
	buf := new(bytes.Buffer)
	tmpl, err := template.New("MicroProvider").Parse(microProviderTpl)
	if err != nil {
		return nil, err
	}
	if err := tmpl.Execute(buf, s); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
